GRANT CONNECT ON DATABASE fintrack TO fintrack_app;
GRANT USAGE ON SCHEMA public TO fintrack_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO fintrack_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO fintrack_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fintrack_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO fintrack_app;
